### ISSUE TITLE
The cli is not working on MacOS with M1 processor

### ISSUE THREAD

**Issue by pan-bubr** [jakzo/aoc#5]
On MacOS Monterey 12.0.1
On Macbook with Apple M1 processor
After installing CLI tool with `npm i -g @jakzo/aoc` trying to use `aoc` throws the following error:

```
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/<user>/.nvm/versions/node/v16.0.0/lib/node_modules/@jakzo/aoc/templates/assembly-x86-mac'
    at Object.readdirSync (node:fs:1390:3)
    at /Users/<user>/.nvm/versions/node/v16.0.0/lib/node_modules/@jakzo/aoc/dist/templates.js:60:33
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/<user>/.nvm/versions/node/v16.0.0/lib/node_modules/@jakzo/aoc/dist/templates.js:54:82)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/<user>/.nvm/versions/node/v16.0.0/lib/node_modules/@jakzo/aoc/templates/assembly-x86-mac'
}
```

**Comment by marcusisinger** [comment]
Same for med on Macbook ´18 with intel i5.

**Comment by jakzo** [comment]
Thanks for reporting. There was a problem with the .npmignore. Should be fixed now.
